services:
  - type: web
    name: gitlinux-pro-cloud
    env: docker
    plan: free
    region: oregon
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8080
      - key: NODE_ENV
        value: production
